#!/bin/sh
#

case "$1" in
  start)
        python etc/init.d/app.py  &
        ;;
  stop)
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
